# Generated by Django 2.1.5 on 2019-01-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked_years', models.IntegerField(verbose_name='Worked years')),
                ('salary_brutto', models.IntegerField(verbose_name='Salary brutto')),
            ],
        ),
    ]
